### ISSUE TITLE
either an error or I goofed 

### ISSUE THREAD

**Issue by tickers** [absalon-james/usage#2]
Traceback (most recent call last):
  File "/usr/bin/usage-report", line 9, in <module>
    load_entry_point('usage', 'console_scripts', 'usage-report')()
  File "/root/usage/usage/console.py", line 45, in console_report
    manager = ClientManager(*_conf.get('auth_kwargs', {}))
TypeError: type object argument after *_ must be a mapping, not NoneType
[root@mitaka ~(keystone_admin)]#

Took a few to setup, 15 mins :) , you omitted to cp the sample report to report.yaml no biggie but it might freak the natives out.  I like the layout! Just need a push on the err above please.

**Comment by absalon-james** [comment]
Greetings.

I was able to get a similar exception after adjusting my /etc/usage/usage.yaml file to be:

``` yaml
auth_kwargs:
auth_url: your_auth_url
username: your_user_name
password: your_password
project_name: your_project_name
user_domain_name: your_user_domain_name
project_domain_name: your_project_domain_name
```

Instead of:

``` yaml
auth_kwargs:
  auth_url: your_auth_url
  username: your_user_name
  password: your_password
  project_name: your_project_name
  user_domain_name: your_user_domain_name
  project_domain_name: your_project_domain_name
```

Would it be possible to double check your /etc/usage/usage.yaml file?

I've also updated the readme with instructions for copying the sample-report.yaml. https://github.com/absalon-james/usage/commit/f4458b1058dc5421bd93dda7b2cdb5538ccd9e59
